### Login request to retrieve a token
POST http://localhost:4004/auth/login
Content-Type: application/json

{
  "email": "bevanrhee@gmail.com",
  "password": "password"
}

> {% client.global.set("token", response.body.token) %}

###