### Register request to auth service
POST http://localhost:4004/auth/register
Content-Type: application/json

{
  "email": "employee@example.com",
  "password": "password"
}

> {% client.global.set("token", response.body.token) %}

###
