### Register request to auth service
POST http://localhost:4004/auth/register
Content-Type: application/json

{
  "email": "again@gmail.com",
  "password": "bob12345"
}

> {% client.global.set("token", response.body.token) %}

###