#server:
#  port: 4004
#
#spring:
#  cloud:
#    gateway:
#      server:
#        webflux:
#          default-filters:
#            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#          globalcors:
#            cors-configurations:
#              "[/**]":
#                allowedOrigins:
#                  - "http://localhost:5173"
#                allowedMethods:
#                  - GET
#                  - POST
#                  - PUT
#                  - DELETE
#                  - OPTIONS
#                allowedHeaders:
#                  - "*"
#                allowCredentials: true
#                maxAge: 3600
#          routes:
#            - id: auth-service-route
#              uri: http://auth-service:4005
#              predicates:
#                - Path=/auth/**
#              filters:
#                - StripPrefix=1
#
#            - id: user-service-route
#              uri: http://user-service:4006
#              predicates:
#                - Path=/api/users/**
#              filters:
#                - StripPrefix=1
#                - JwtValidation
#
#            - id: payroll-service-route
#              uri: http://payroll-service:4000
#              predicates:
#                - Path=/api/payroll/**
#              filters:
#                - StripPrefix=1
#                - JwtValidation
#
#            - id: timesheet-service-route
#              uri: http://timesheet-service:4001
#              predicates:
#                - Path=/api/timesheet/**
#              filters:
#                - StripPrefix=1
#                - JwtValidation
#
#            - id: contract-service-route
#              uri: http://contract-service:4002
#              predicates:
#                - Path=/api/contract/**
#              filters:
#                - StripPrefix=1
#                - JwtValidation
#
#


server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            ## http://localhost:4004/auth/login -> localhost:4004 is the address of the api gateway
            ## API GATEWAY -> http://auth-service:4005/login

            # Auth-Service
            - id: auth-service-route
              uri: http://auth-service:4005
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: api-docs-auth-route
              uri: http://auth-service:4005
              predicates:
                - Path=/api-docs/auth
              filters:
                - RewritePath=/api-docs/auth,/v3/api-docs

            ## REST CLIENT -> http://localhost:4004/api/payroll
            ## API GATEWAY -> http://payroll-service:4000/payroll
            ## payroll SERVICE (SPRING BOOT APP) -> /payroll -> Payroll array

            # User-Service
            - id: user-service-route
              uri: http://user-service:4006
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1
                - JwtValidation
            - id: api-docs-user-route
              uri: http://user-service:4006
              predicates:
                - Path=/api-docs/user
              filters:
                - RewritePath=/api-docs/users,/v3/api-doc

            # Payroll-Service
            - id: payroll-service-route
              uri: http://payroll-service:4000
              predicates:
                - Path=/api/payroll/**
              filters:
                - StripPrefix=1
                - JwtValidation
            - id: api-docs-payroll-route
              uri: http://payroll-service:4000
              predicates:
                - Path=/api-docs/payroll
              filters:
                - RewritePath=/api-docs/payroll,/v3/api-docs

            # Timesheet-Service
            - id: timesheet-service-route
              uri: http://timesheet-service:4001
              predicates:
                - Path=/api/timesheet/**
              filters:
                - StripPrefix=1
                - JwtValidation
            - id: api-docs-timesheet-route
              uri: http://timesheet-service:4001
              predicates:
                - Path=/api-docs/timesheet
              filters:
                - RewritePath=/api-docs/timesheet,/v3/api-docs

            # Contract-Service
            - id: contract-service-route
              uri: http://contract-service:4002
              predicates:
                - Path=/api/contract/**
              filters:
                - StripPrefix=1
                - JwtValidation
            - id: api-docs-contract-route
              uri: http://contract-service:4002
              predicates:
                - Path=/api-docs/contract
              filters:
                - RewritePath=/api-docs/contract,/v3/api-docs

              ## REST-CLIENT -> http://localhost:4004/api-docs/contract
              ## API-GATEWAY -> http://contract-service:4002/v3/api-docs

# Enable debug logging for troubleshooting
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.pm.authservice.security: DEBUG
    ROOT: INFO