services:
  auth-service-db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin_user
    ports: ["5001:5432"]
    volumes: ["auth_db_data:/var/lib/postgresql/data"]

  user-service-db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin_user
    ports: ["5002:5432"]
    volumes: ["user_db_data:/var/lib/postgresql/data"]

  payroll-service-db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin_user
    ports: ["5000:5432"]
    volumes: ["payroll_db_data:/var/lib/postgresql/data"]

  timesheet-service-db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin_user
    ports: ["5003:5432"]
    volumes: ["timesheet_db_data:/var/lib/postgresql/data"]

  contract-service-db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin_user
    ports: ["5004:5432"]
    volumes: ["contract_db_data:/var/lib/postgresql/data"]

  kafka:
    image: bitnamilegacy/kafka:latest
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_CFG_NODE_ID: "0"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
    ports: ["9092:9092", "9094:9094"]

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: auth-service:latest
    environment:
      JWT_SECRET: "cc028f2d8dcf1c84ffbf92c9ed5255e8df01bc0ca4a760ebce999a8fdc8741ad"
      PASSWORD_RESET_FRONTEND_URL: "http://localhost:5173/reset-password"
      PASSWORD_RESET_FROM_EMAIL: "MS_7zsxDo@test-r6ke4n1e8negon12.mlsender.net"
      PASSWORD_RESET_HMAC_SECRET: "${PASSWORD_RESET_HMAC_SECRET:-e3f6c9a4d1b0b7e8f2c0a61d7d4f9b3a8c1e5b0d9a7f3c6e2b8d1a4f0c9e7b2d6a1f4c8b0e3d9a2c7f6b1d0e5a8c3f9b2d7e1c4a0b9d6f2c8a1e3b7d0c5a9f1b4e8d2c6a0f3b9d1e7c2a5f0b8d4c9e1a6}"
      SPRING_MAIL_HOST: "smtp.mailersend.net"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: "smtp.mailersend.net"
      SPRING_MAIL_PORT: "587"
      SPRING_MAIL_USERNAME: "${SPRING_MAIL_USERNAME:-MS_7zsxDo@test-r6ke4n1e8negon12.mlsender.net}"
      SPRING_MAIL_PASSWORD: "${SPRING_MAIL_PASSWORD:-mssp.aqiT8Sv.3yxj6ljm190ldo2r.3EC7wOE}"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: "true"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://auth-service-db:5432/db"
      SPRING_DATASOURCE_USERNAME: "admin_user"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      SPRING_SQL_INIT_MODE: "always"
    depends_on: [auth-service-db, kafka]

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: user-service:latest
    environment:
      AUTH_SERVICE_BASE_URL: "http://api-gateway:4004"
      AUTH_SERVICE_ADDRESS: "auth-service"
      AUTH_SERVICE_GRPC_PORT: "9005"
      CONTRACT_SERVICE_BASE_URL: "http://api-gateway:4004"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://user-service-db:5432/db"
      SPRING_DATASOURCE_USERNAME: "admin_user"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      SPRING_SQL_INIT_MODE: "always"
    depends_on: [user-service-db, kafka, api-gateway]

  timesheet-service:
    build:
      context: ./timesheet-service
      dockerfile: Dockerfile
    image: timesheet-service:latest
    environment:
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://timesheet-service-db:5432/db"
      SPRING_DATASOURCE_USERNAME: "admin_user"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_SQL_INIT_MODE: "always"
    depends_on: [timesheet-service-db]

  contract-service:
    build:
      context: ./contract-service
      dockerfile: Dockerfile
    image: contract-service:latest
    environment:
      USER_SERVICE_ADDRESS: "user-service"
      USER_SERVICE_GRPC_PORT: "9006"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://contract-service-db:5432/db"
      SPRING_DATASOURCE_USERNAME: "admin_user"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_SQL_INIT_MODE: "always"
    depends_on: [contract-service-db, kafka]

  payroll-service:
    build:
      context: ./payroll-service
      dockerfile: Dockerfile
    image: payroll-service:latest
    environment:
      CONTRACT_SERVICE_ADDRESS: "contract-service"
      CONTRACT_SERVICE_GRPC: "9002"
      TIMESHEET_SERVICE_ADDRESS: "timesheet-service"
      TIMESHEET_SERVICE_GRPC: "9001"
      USER_SERVICE_ADDRESS: "user-service"
      USER_SERVICE_GRPC: "9006"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://payroll-service-db:5432/db"
      SPRING_DATASOURCE_USERNAME: "admin_user"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      SPRING_SQL_INIT_MODE: "always"
    depends_on: [payroll-service-db, contract-service, timesheet-service, user-service, kafka]

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    environment:
      AUTH_SERVICE_URL: "http://auth-service:4005"
    ports: ["4004:4004"]
    depends_on: [auth-service]

volumes:
  auth_db_data: {}
  user_db_data: {}
  payroll_db_data: {}
  timesheet_db_data: {}
  contract_db_data: {}
