### CREATE request to payroll-service
POST http://localhost:4004/api/payroll
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "f5c6d7e8-aaaa-4e9b-1c2d-000000000050",
  "dateOfIssue": "2026-07-30",
  "hoursWorked": 40,
  "hourlyWage": 25
}



###