### UPDATE Request to Payroll-Service
PUT http://localhost:4004/api/payroll/c5d6e7f8-9999-4d8a-0b1c-000000000005
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "b1e2f3a4-2222-4c5d-9b3c-000000000010",
  "dateOfIssue": "2025-08-01",
  "hoursWorked": 42.5,
  "hourlyWage": 27.0
}