FROM maven:3.9.10-eclipse-temurin-21 AS builder
WORKDIR /app

COPY pom.xml ./
RUN mvn -B dependency:go-offline

COPY src ./src
RUN mvn -B clean package -DskipTests

FROM eclipse-temurin:21-jre AS runner
WORKDIR /app

COPY --from=builder /app/target/*.jar /app/app.jar

EXPOSE 4005

ENTRYPOINT ["java", "-jar", "app.jar"]