spring.application.name=contract-service
spring.jpa.defer-datasource-initialization=true
server.port=4002
grpc.server.port=9002
logging.level.root=info
contract.service.address=localhost
contract.service.grpc.port=9002
user.service.address=localhost
user.service.grpc.port=9006
