### CREATE request to Contract-service
POST http://localhost:4004/api/contract
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": "22222222-2222-2222-2222-222222222334",
  "startDate": "2025-01-01",
  "endDate": "2025-12-31",
  "wageTaxAmountTest": 0.00,
  "functions": ["Junior Developer", "test function"]
}
###
