### PUT request to user service
PUT http://localhost:4004/api/users/91c28613-1c63-4cc5-ad5d-67521fd0d0a8
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Benjamin van Rhee",
  "email": "benjamin@example.com",
  "streetName": "Hickorystraat",
  "houseNumber": "123",
  "houseNumberSuffix": "B",
  "postalCode": "1234 AB",
  "city": "Shelbyville",
  "country": "Netherlands",
  "dateOfBirth": "1991-12-25",
  "bankAccountNumber": "NL55ABNA0123456789",
  "phoneNumber": "0612345678"
}

###
