### PUT request to user-service
PUT http://localhost:4004/api/users/11111111-1111-1111-1111-222222222222
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Sophia Clark",
  "email": "alice.brown@example.com",
  "address": "123 Hickory St, Shelbyville",
  "dateOfBirth": "1991-12-25",
  "bankAccountNumber": "NL88ABN890890098",
  "phoneNumber": "123345"
}

###