spring.application.name=user-service
spring.jpa.defer-datasource-initialization=true
server.port=4006
grpc.server.port=9006
logging.level.root=info

# Kafka consumer uses plain byte array
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

auth.service.base-url=http://localhost:4004
auth.service.address=localhost
auth.service.grpc.port=9005
contract.service.base-url=http://localhost:4004
